steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
  - '-t'
  - '${_IMAGE_NAME}'
  - '.'
images:
- '${_IMAGE_NAME}'
substitutions:
  _NEXT_PUBLIC_API_URL: 'http://localhost:8080'
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/kuhp-analyzer-frontend'